In [1]:
#import sklearn

#from sklearn.datasets import load_breast_cancer #para importar la data
#from sklearn.model_selection import train_test_split #se dividen los datos en set de entrenamiento y set de pruebas 
#from sklearn.naive_bayes import GaussianNB # Se construye el modelo clasificador y se ajusta a los datos
#from sklearn.metrics import accuracy_score #para ver la precisión del modelo

#Paso 1, Se importan las librerias necesarias
import warnings
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
warnings.filterwarnings("ignore") # specify to ignore warning messages


In [11]:
# paso 2)se carga la data
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Regression/master/SampleData.csv')
X = dataset.iloc[:, 0].values
y = dataset.iloc[:, 1].values
y = np.array(y).reshape(-1,1)
dataset.head(5)


array([[31.70700585],
       [68.77759598],
       [62.5623823 ],
       [71.54663223],
       [87.23092513],
       [78.21151827],
       [79.64197305],
       [59.17148932],
       [75.3312423 ],
       [71.30087989],
       [55.16567715],
       [82.47884676],
       [62.00892325],
       [75.39287043],
       [81.43619216],
       [60.72360244],
       [82.89250373],
       [97.37989686],
       [48.84715332],
       [56.87721319],
       [83.87856466],
       [98.5912173 ],
       [57.25181946],
       [51.39174408],
       [75.38065167],
       [74.76556403],
       [95.45505292],
       [95.22936602],
       [79.05240617],
       [83.43207142],
       [63.35879032],
       [41.4128853 ],
       [76.61734128],
       [96.76956643],
       [74.08413012],
       [66.58814441],
       [77.76848242],
       [50.71958891],
       [62.12457082],
       [60.81024665],
       [52.68298337],
       [58.56982472],
       [82.90598149],
       [61.4247098 ],
       [95.2441528 ],
       [45

In [12]:
#Paso 3) se escala la data para que trabaje mejor el modelo



from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X.reshape(-1,1))
y = sc_y.fit_transform(y.reshape(-1,1))
y()

array([[-2.66651176],
       [-0.21538463],
       [-0.62633786],
       [-0.03229448],
       [ 1.00475931],
       [ 0.40839133],
       [ 0.50297376],
       [-0.85054551],
       [ 0.21794595],
       [-0.04854375],
       [-1.11541194],
       [ 0.69054936],
       [-0.66293287],
       [ 0.22202084],
       [ 0.62160848],
       [-0.74791896],
       [ 0.71790058],
       [ 1.67581471],
       [-1.5331961 ],
       [-1.00224427],
       [ 0.78309945],
       [ 1.75590787],
       [-0.9774751 ],
       [-1.3649464 ],
       [ 0.22121292],
       [ 0.180543  ],
       [ 1.54854301],
       [ 1.53362047],
       [ 0.46399128],
       [ 0.75357708],
       [-0.57367894],
       [-2.02475385],
       [ 0.3029835 ],
       [ 1.63545934],
       [ 0.13548623],
       [-0.36015233],
       [ 0.37909756],
       [-1.40938966],
       [-0.65528619],
       [-0.74219   ],
       [-1.27956897],
       [-0.89032789],
       [ 0.71879173],
       [-0.70156137],
       [ 1.53459818],
       [-1

In [4]:
#Paso 4) test set & training set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [5]:
#paso 5 entrenando SVR en el training set

from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train.reshape(-1,1), y_train.reshape(-1,1))

SVR()

In [6]:
#paso 6 predicción del test set
y_pred = regressor.predict(X_test)
y_pred = np.array(y_pred).reshape(-1,1)
y_pred = sc_y.inverse_transform(y_pred)
y_pred

array([[76.35924334],
       [80.0221117 ],
       [93.53800123],
       [56.67885858],
       [60.34788093],
       [54.95736712],
       [75.76158757],
       [53.92867724],
       [94.26602339],
       [77.20624577],
       [79.59427522],
       [71.14037054],
       [78.95427869],
       [59.65405532],
       [88.9057695 ],
       [62.38575748],
       [73.83815496],
       [84.03448697],
       [53.27535653],
       [58.96684245]])

In [8]:
from sklearn.metrics import accuracy_score #para ver la precisión del modelo
print(accuracy_score(y_test,y_pred))

ValueError: continuous is not supported

In [9]:
df = pd.DataFrame({'Real Values':y, 'Predicted Values':y_pred})


ValueError: Per-column arrays must each be 1-dimensional